repo_url: https://github.com/WireCell/wire-cell-docs/
repo_name: GitHub
site_name: Wire Cell Documentation
site_description: Documentation for the LArTPC Wire Cell reconstruction packages
site_url: https://wirecell.github.io/
theme: readthedocs
pages:
  - Overview: index.md
  - Researcher: researcher/index.md
  - User: user/index.md
  - Installer: installer/index.md
  - Developer: developer/index.md
  - Administrator: administrator/index.md
  - Documenter: meta/index.md

# theme_dir: custom_theme

